Fix starting puma server (#1)
Old variant cause
```
ERROR: for api-server  Cannot start service api-server: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "puma": executable file not found in $PATH: unknown
```